on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
      - name: Run Unit Tests
        run: go test -coverprofile coverage.txt -race `go list ./... | grep -v github.com/swedishborgie/daytripper/examples`
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: swedishborgie/daytripper
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1